### ISSUE TITLE
Upgrade to v4.1.4 once released (Fixes /health)

### ISSUE THREAD

**Issue by RussellMcOrmond** [c7a/cihm-cantaloupe#10]
https://github.com/cantaloupe-project/cantaloupe/releases

**Comment by SaschaAdler** [comment]
I am indeed going to push forward with this when pointing Cantaloupe to Swift, because v4.1 allows for configuration by environment variables, which will be very handy in pointing Docker containers to arbitrary Swift containers.

**Comment by RussellMcOrmond** [comment]
4.1.2 has a bug in http://image.vbc.canadiana.ca/health where it reports failure for .jp2 files (which need to use the Fallback Retrieval Strategy as OpenJPEG doesn't support S3 streams), even though everything works.

This will be fixed in 4.1.4 once released  https://github.com/cantaloupe-project/cantaloupe/issues/307

**Comment by RussellMcOrmond** [comment]
We have been monitoring possible RAM issues, which may not be an issue now that we have upgraded the version of Java we are using.  

One way to ensure that the container restarts automatically when it fails is to make use of the https://docs.docker.com/engine/reference/builder/#healthcheck feature.

Once the /health endpoint is written a test: should be written that confirms everything is GREEN such that the container can be restarted if it isn't.

**Comment by RussellMcOrmond** [comment]
In a different issue on Cantaloupe, "4.1.4 probably within a week or two".

**Comment by RussellMcOrmond** [comment]
https://github.com/cantaloupe-project/cantaloupe/releases/tag/v4.1.4

**Comment by SaschaAdler** [comment]
I've committed an update to master that updates this to 4.1.4. I didn't get a chance to push my Docker image but minimal testing shows it to work.

**Comment by RussellMcOrmond** [comment]
I saw 94867829620a12b97667b9949577289f2ff4c9ad

So far only VBC is running the new version, and this will change once we deploy the new Swift servers and have multiple application servers in Toronto and Edmonton.

```
russell@kernhem:~/puppet/manifests/nodes$ grep cihm-cantaloupe: *
eclipse.pp:  $cantaloupeimage = 'docker.c7a.ca/cihm-cantaloupe:4.0.2'			# JAVA-driven image cacher
paneer.pp:  $cantaloupeimage = 'docker.c7a.ca/cihm-cantaloupe:4.0.2'
romano.pp:  $cantaloupeimage = 'docker.c7a.ca/cihm-cantaloupe:4.0.2'
toma.pp:  $cantaloupeimage = 'docker.c7a.ca/cihm-cantaloupe:4.0.2'
vbc.pp:  $cantaloupeimage = 'docker.c7a.ca/cihm-cantaloupe:20191009'
russell@kernhem:~/puppet/manifests/nodes$ 
```
