### ISSUE TITLE
Create 'zfs' branch?

### ISSUE THREAD

**Issue by RussellMcOrmond** [c7a/cihm-cantaloupe#12]
Suggestion to create a 'zfs' branch which will contain a maintained branch that will access 'zfs'.  Then the 'swift' branch can be merged into master.

We don't know if we'll need to switch back if there are issues, so best to keep the zfs capable version around for a bit.

**Comment by SaschaAdler** [comment]
On it.

**Comment by SaschaAdler** [comment]
The zfs branch has been created, and the swift pull request should be ready. I wouldn't mind a look at it before we commit it.

**Comment by RussellMcOrmond** [comment]
Curious if we want to complete #13 before doing the PR, or have that discussion within the PR?

**Comment by SaschaAdler** [comment]
We might as well complete #13 before merging the PR.
