### ISSUE TITLE
OpenJDK versions

### ISSUE THREAD

**Issue by RussellMcOrmond** [c7a/cihm-cantaloupe#14]
We were using openjdk:8u181-alpine and based on https://cantaloupe-project.github.io/manual/4.1/deployment.html#Docker I upgraded to using openjdk:8u191-alpine 

OpenJDK has many versions, but I don't understand the version numbers: https://github.com/docker-library/docs/blob/master/openjdk/README.md

I note that 8u222 exists, but not with alpine.  Then numbers go to 11 with stretch, and then 12,13, and 14 early access with Oracle Linux.

Wondering what  would be best to be using as a base image to build our image.

**Comment by SaschaAdler** [comment]
[It looks like](https://en.wikipedia.org/wiki/Java_version_history) 8 and 11 are LTS versions. Cantaloupe supports both, and so it should be no trouble to switch to 11 if we want.

**Comment by RussellMcOrmond** [comment]
We would be migrating away from Alpine to one of the other distributions where a pre-built docker image is provided.  In the case of OpenJDK 11 there is 11.0.4-jdk-slim-buster which is based on Debian 10.0 (Buster https://www.debian.org/releases/buster/ ).

https://github.com/cantaloupe-project/cantaloupe/issues/315 also suggests we move to 11.

**Comment by RussellMcOrmond** [comment]
openjdk:12.0.2-jdk-oraclelinux7 is JDK 12 (also reached general availability) https://openjdk.java.net/projects/jdk/12/ built FROM oraclelinux:7-slim 

Oracle Linux is Oracle's fork of RHEL, similar to CentOS but managed by Oracle.

* https://www.oracle.com/technetwork/server-storage/linux/downloads/index.html
* https://hub.docker.com/_/oraclelinux/
* https://github.com/oracle/container-images/tree/dist-amd64/7-slim

Thoughts?

**Comment by SaschaAdler** [comment]
While there is no OpenJDK Alpine linux image for OpenJDK 11, apparently there are OpenJDK 11 Alpine packages (as of a couple months ago). I'm testing them now.

**Comment by SaschaAdler** [comment]
Seems to work for me. I've committed the updates.

**Comment by RussellMcOrmond** [comment]
I tested on my desktop, and when satisfied deployed this to VBC which is doing production image processing (all portals but Heritage).
