### ISSUE TITLE
Validate staff auth cookies

### ISSUE THREAD

**Issue by SaschaAdler** [c7a/cihm-cantaloupe#19]
See https://github.com/crkn-rcdr/amsa/issues/8

If we go ahead with the above change, we can have Cantaloupe validate these cookies, since they'll be available across canadiana.ca domains. This means we don't have to do anything special to generate Cantaloupe tokens in staff tools. Rules for validation can also limit things by filetype/extension, similar to how the `cantaloupeToken` is created in amsa.

**Comment by RussellMcOrmond** [comment]
While we are here, we should probably test the update  #18
