### ISSUE TITLE
JPEGs in CMYK color space throw libjpeg-turbo errors

### ISSUE THREAD

**Issue by SaschaAdler** [c7a/cihm-cantaloupe#30]
On the first page of this parl manifest: https://parl-demo.canadiana.ca/view/oop.debates_HOC0104_01/1

The full-size image can be provided: https://image-tor.canadiana.ca/iiif/2/69429%2Fc0nv9982c493/full/max/0/default.jpg. I assume Cantaloupe is just providing the source image as is.
Image manipulations fail: https://image-tor.canadiana.ca/iiif/2/69429%2Fc0nv9982c493/full/80,/0/default.jpg

Doing a quick `identify`:
`JPEG 2550x3300 2550x3300+0+0 8-bit CMYK 424941B 0.000u 0:00.000`

One of the other full-size images that doesn't throw errors:
`JPEG 2550x3300 2550x3300+0+0 8-bit Gray 256c 164075B 0.000u 0:00.000`

I guess libjpeg-turbo is choking on the CMYK color space.

Other cover images digitized around the same time seem to be using sRGB instead of CMYK.

I'm not sure what to do about this, although if we're ever working on our image validation pipeline we could try to sort this out.

(The first image of https://parl-demo.canadiana.ca/view/oop.debates_CDC0104_01/1 has a similar problem.)

**Comment by RussellMcOrmond** [comment]
Our solution is: Archivematica.

We won't be trying to display the images we have preserved, but copies that have been normalised for access. This is a known issue.
