### ISSUE TITLE
"uninitialized constant Cantaloupe" when upgrading openjdk version

### ISSUE THREAD

**Issue by RussellMcOrmond** [c7a/cihm-cantaloupe#4]
We are currently using openjdk:8u131-jdk-alpine .  When I tried to upgrade to openjdk:8u171-jdk-alpine3.8 I received an error:

```
Caused by: org.jruby.exceptions.RaiseException: (NameError) uninitialized constant Cantaloupe
	at org.jruby.RubyModule.const_missing(org/jruby/RubyModule.java:3345)
	at RUBY.<main>(<script>:1)
```

Cantaloupe is unable to run.

**Comment by RussellMcOrmond** [comment]
Sascha,

While you are thinking about Cantaloupe it might be worth looking into this.  I don't know if it is a compatibility issue that was solved with the new version.

**Comment by SaschaAdler** [comment]
Updated the v4 branch (which I'm about to merge into master) with an updated openjdk, which is running on Romano without trouble.

**Comment by RussellMcOrmond** [comment]
I pulled this changeset and rebuilt docker.c7a.ca/cihm-cantaloupe:4.0.2 .  When I tried to run on Brie/Caboc I got a 500 error.

```
17:57:54.780 [qtp761960786-46] INFO  e.i.l.c.s.DelegateProxy - Loading script code
LoadError: no such file to load -- jwt
  require at org/jruby/RubyKernel.java:956
  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55
   <main> at <script>:8
17:57:54.789 [qtp761960786-46] ERROR e.i.l.c.s.DelegateProxyService - org.jruby.embed.EvalFailedException: (LoadError) no such file to load -- jwt
NameError: uninitialized constant CustomDelegate
  const_missing at org/jruby/RubyModule.java:3372
         <main> at <script>:2
17:57:54.828 [qtp761960786-46] ERROR e.i.l.c.s.DelegateProxy - org.jruby.embed.EvalFailedException: (NameError) uninitialized constant CustomDelegate
17:57:54.830 [qtp761960786-46] ERROR o.r.C.RestletApplication - Exception or error caught in server resource
org.restlet.resource.ResourceException: Internal Server Error (500) - The server encountered an unexpected condition which prevented it from fulfilling the request
...
```

**Comment by SaschaAdler** [comment]
Is there anything in the build logs about the jwt gem not being built properly? I'm not sure if this is an openjdk update problem.

**Comment by RussellMcOrmond** [comment]
```
Successfully installed jwt-2.1.0
Successfully installed json_pure-2.1.0
2 gems installed

```

If I make the change back to "FROM openjdk:8u131-jdk-alpine" then the image runs without trouble.

**Comment by SaschaAdler** [comment]
I'm happy to go back to 8u131.

I'm confused, though, as to why my local build on Romano was totally happy about the upgrade. We could look into ensuring that the gems are built using the same version of JRuby that Cantaloupe is using, or ensuring that the gems are installed in the right place in the update.

**Comment by SaschaAdler** [comment]
Mind testing something for me?

Change the path in the GEM_HOME line in the Dockerfile to 2.5.0 from 2.4.0.

That is, with the openjdk version set to 8u181.

**Comment by RussellMcOrmond** [comment]
I tried making that change, and it works on Brie/Caboc .

**Comment by SaschaAdler** [comment]
The above commit solves the problem of Ruby gems paths, by default, being tied to the Ruby version number. The updated openjdk source image had a newer version of Ruby.
