### ISSUE TITLE
Use Alpine openjpeg package

### ISSUE THREAD

**Issue by SaschaAdler** [c7a/cihm-cantaloupe#7]
Newer openjdk images are based on Alpine 3.8, which has openjpeg v2.3.0 in its package manager. I suspect we can revert to using the package instead of building openjpeg from source.

**Comment by RussellMcOrmond** [comment]
http://online.havarti.canadiana.ca/view/oocihm.99400/1 is the image referenced in https://github.com/medusa-project/cantaloupe/issues/111 .  I pointed Havarti at Brie/Caboc which is using the latest build of the v4 branch.

**Comment by SaschaAdler** [comment]
I've tested the above commit on the further above image. Russell, I'll let you test things out elsewhere if you like.

**Comment by RussellMcOrmond** [comment]
I built the image, and got "Cannot run program "opj_decompress": error=2, No such file or directory".

I've changed the Dockerfile to install the openjpeg-tools which brings in the command-line tool called.

**Comment by RussellMcOrmond** [comment]
Tagged as docker.c7a.ca/cihm-cantaloupe:4.0.2  and deployed to server used in production.
