### ISSUE TITLE
Config issues: undefined method `each' for nil:NilClass

### ISSUE THREAD

**Issue by RussellMcOrmond** [c7a/cihm-cantaloupe#9]
The stderr of the production Cantaloupe has errors such as the following:

```
15:16:02.108 [qtp761960786-45] ERROR e.i.l.c.s.FilesystemSource - java.lang.NoSuchMethodException: (NoMethodError) undefined method `each' for nil:NilClass

...

Caused by: org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `each' for nil:NilClass
	at RUBY.filesystemsource_pathname(<script>:110)
```

The only 'each' in the code is related to the directory listing that should have been stuffed into the config.  I can't tell from the error if it was the directory listing that failed or if @config itself was nil.

**Comment by SaschaAdler** [comment]
The Swift implementation also removes the whole `@config` thing, and so that should solve this problem. I think it's a wontfix for the ZFS branch.
